### ISSUE TITLE
[Convert to Karamba] does not work properly.

### ISSUE THREAD

**Issue by Takahisa-Sakai** [hrntsm/HoaryFox#206]
〇概要
HoaryFox ver2.0.1のインストールをRhino7に対して実行、サンプルファイル：Convert_to_Karamba.ghをオープンしたが、
[Convert to Karamba]の動作エラー発生
(いつも大変活用させていただいております。
初歩的な点で申し訳ございませんが、インストールについてのissueとなります。
何か手順を間違えておりましたらご教示いただけますと幸いです。
恐れ入りますが、よろしくお願いいたします。)

〇詳細
1..ghaおよび.dllファイルをKaramba.ghaファイルと同ディレクトリに配置(Grasshopper\Librariesに配置ではインストールされず)、
各ファイルブロック解除済み
2.サンプルファイルのConvert_to_Karamba.ghをrhino7のGHによりオープン
3.同サンプルフォルダ内のSampleBuilding.stbを読み込み
4.コンポーネントは正常に表示されたが、下記バルーン警告により[Convert to Karamba]動作失敗
「 Solution exception:オブジェクト参照がオブジェクト インスタンスに設定されていません。」

〇各バージョン
Rhino 7：ver 7.13.21348.13001
Grasshopper：ver 1.0.0007

〇補足
HoaryFox ver 1.3.1では同様のインストール方法で、Convert to Karambaの正常な動作を確認済み

〇スクリーンショット
フォルダ状況
![image](https://user-images.githubusercontent.com/41667636/146326350-d6d5b24b-af00-4c32-8252-4250c83517c0.png)

エラー状況
![コメント 2021-12-16 162517](https://user-images.githubusercontent.com/41667636/146326560-0fc494fd-0210-4141-9943-0a4d15f0bd63.png)

**Comment by hrntsm** [comment]
@Takahisa-Sakai
報告ありがとうございます。原因確認させていただきます。
使っているKaramba3Dのバージョンと、もしRhino側で何かエラーの表示が出ていれば教えたいただければと思います。

**Comment by Takahisa-Sakai** [comment]
ご対応をいただきましてありがとうございます。

RhinoおよびGrasshopperの起動時にはコンポーネント読み込みエラー等のメッセージは出ておりません。

Karambaのバージョンは以下になります。
Karamba3D：1.3.3 - build 210709 for RHINO 6

**Comment by hrntsm** [comment]
@Takahisa-Sakai 
以下のように複数バージョンに対して以下のようにビルドするようにしました。
![image](https://user-images.githubusercontent.com/23289252/147567434-15ae2bf3-4c5f-4d0f-8f72-83af6837bcd8.png)

テストでビルドしたモデルを以下のリンクからダウンロードしていただき、該当するバージョンで試していただけますか？
https://github.com/hrntsm/HoaryFox/suites/4777153930/artifacts/133188321

HoaryFox のフォルダは以下の箇所（通常のgrasshopperコンポーネントをいれるLibrary）にフォルダごといれ、
![image](https://user-images.githubusercontent.com/23289252/147567367-c7f2c230-c19c-4055-91cb-8243be9f6ad5.png)

KarambaConnect については以下のようにKarambaフォルダに直接入れてください。
![image](https://user-images.githubusercontent.com/23289252/147567223-b1b82123-2f9f-48b7-8c9b-5e192f7da765.png)

**Comment by Takahisa-Sakai** [comment]
お忙しい中、ご対応いただきましてありがとうございます。
上記の方法で再トライしてみたところ、問題なく動作を確認できました！
誠にありがとうございます!
