### ISSUE TITLE
 [Convert to Karamba] has doubled the number of columns.

### ISSUE THREAD

**Issue by Takahisa-Sakai** [hrntsm/HoaryFox#207]
〇概要
HoaryFox ver1.3.1のサンプルファイルConvert_to_Karamba.ghをオープン、柱が倍の数生成されていることを確認。
(こちらは仕様でしょうか?正しい使用方法がございましたらご教示いただければ幸いです。
いつも大変活用させていただいております。恐れ入りますが、よろしくお願いいたします。)

〇詳細
1.ver1.3.1のサンプルファイルConvert_to_Karamba.ghをオープン、[Stb to Line]の線材本数よりも多くのエレメントが[Convert to Karamba]によって生成されている
2.[Disassemble Model]などで柱が2本ずつ重複していることを確認。
3.柱の重複を削除したモデルを再作成すると、無限大に変形していたモデルが正常に変形

〇各バージョン
Rhino 7：ver 7.13.21348.13001
Grasshopper：ver 1.0.0007
Karamba3D：1.3.3 - build 210709 for RHINO 6

〇スクリーンショット
![image](https://user-images.githubusercontent.com/41667636/146330798-33a56d5c-9af2-4afe-b892-b60589d01ead.png)

![image](https://user-images.githubusercontent.com/41667636/146330828-a20c4e28-77c8-4936-8008-5fce48fcbcd0.png)

![image](https://user-images.githubusercontent.com/41667636/146330883-6e728abc-3a57-4c84-b89b-efd350737762.png)

**Comment by hrntsm** [comment]
報告ありがとうございます。バグのようななので確認させていただきます。

**Comment by hrntsm** [comment]
@Takahisa-Sakai 
こちらの件、私の手持ちの stb ファイルで確認してみましたが、以下のように部材数は違っていませんでした。
![image](https://user-images.githubusercontent.com/23289252/147572816-34af90fd-2257-4aee-be5d-3a0820122711.png)

最新のビルドしたもので再度試していただけると助かります。
https://github.com/hrntsm/HoaryFox/suites/4777843693/artifacts/133229853

それでも部材がダブルで出力されているようでしたら想定していない stb ファイルの形式かもしれませんので、stbデータをいただけましたら確認します。

**Comment by Takahisa-Sakai** [comment]
ご対応いただきまして、ありがとうございます。
上記の方法で再度試したところ、サンプルstbファイル・自前のstbファイル共に問題なく柱が生成されるようになりました!
誠にありがとうございます!

**Comment by hrntsm** [comment]
問題が解決されたようでよかったです。
また何かありましたら気軽に Issue 立てていただけたらと思います！
